// ReactPOC/src/components/CadastroEmpresa/Cadastro.jsx
import { useNavigate } from "react-router-dom";
import "./Cadastro.css";
import { useState } from "react";
export const Cadastro = () => {
  const [email, setEmail] = useState("");
  const [senha, setSenha] = useState("");

  const navigate = useNavigate();

  const handleSubmit = (e) => {
    console.log(email);
    console.log(senha);

    e.preventDefault();

    navigate("/dashboard");
  };

  return (
    <div className="container">
      <form className="form" onSubmit={handleSubmit}>
        <h1 className="title">Cadastro Empresa</h1>

        <div>
          <label htmlFor="cnpj">CNPJ: </label>

          <input
            name="cnpj"
            id="cnpj"
            onChange={(e) => {
              setEmail(e.target.value);
            }}
            required
          />
        </div>
        <div>
          <label htmlFor="form">Nome Fantasia: </label>
          <input
            name="nome"
            id="nome"
            onChange={(e) => {
              setSenha(e.target.value);
            }}
            required
          />
        </div>
        <button type="submit">Entrar</button>
      </form>
    </div>
  );
};

// angularPOC/src/app/components/cadastro/cadastro.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-cadastro',
  imports: [FormsModule],
  templateUrl: './cadastro.component.html',
  styleUrl: './cadastro.component.css',
})
export class CadastroComponent {
  email: string = '';
  password: string = '';

  constructor(private router: Router) {}

  cadastrar() {
    console.log('Email:', this.email);
    console.log('Senha:', this.password);

    this.router.navigate(['/login']);
  }
}

<div class="container">
  <form class="form" (ngSubmit)="cadastrar()">
    <h1 class="title">Cadastro</h1>

    <div>
      <label htmlFor="cnpj">Email: </label>
      <input
        name="cnpj"
        id="email"
        [(ngModel)]="email"
        required
        [ngModelOptions]="{ standalone: true }"
      />
    </div>
    <div>
      <label htmlFor="form">Senha: </label>
      <input
        name="password"
        id="password"
        [(ngModel)]="password"
        [ngModelOptions]="{ standalone: true }"
      />
    </div>
    <button type="submit">Entrar</button>
  </form>
</div>
