// ReactPOC/src/components/Login/Login.jsx
import { useNavigate } from "react-router-dom";
import "./Login.css";
import { useState } from "react";
export const Login = () => {
  const [email, setEmail] = useState("");
  const [senha, setSenha] = useState("");

  const navigate = useNavigate();

  const handleSubmit = (e) => {
    console.log(email);
    console.log(senha);

    e.preventDefault();

    navigate("/dashboard");
  };

  return (
    <div className="container">
      <form className="form" onSubmit={handleSubmit}>
        <div>
          <label htmlFor="email">Email: </label>

          <input
            type="email"
            name="email"
            id="email"
            onChange={(e) => {
              setEmail(e.target.value);
            }}
          />
        </div>
        <div>
          <label htmlFor="password">Senha: </label>
          <input
            type="password"
            name="password"
            id="password"
            onChange={(e) => {
              setSenha(e.target.value);
            }}
          />
        </div>
        <button type="submit">Entrar</button>
      </form>
    </div>
  );
};

// angularPOC/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-login',
  imports: [FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  email: string = '';
  password: string = '';

  constructor(private router: Router) {}

  login() {
    console.log('Email:', this.email);
    console.log('Senha:', this.password);

    this.router.navigate(['/dashboard']);
  }
}

<div class="container">
  <form class="form" (ngSubmit)="login()">
    <div>
      <label for="email">Email:</label>
      <input type="email" id="email" [(ngModel)]="email" required />
    </div>
    <div>
      <label for="password">Senha :</label>
      <input type="password" id="password" [(ngModel)]="password" />
    </div>
    <button type="submit">Enviar</button>
  </form>
</div>
