// ReactPOC/src/components/Home/index.jsx
import React from "react";
import { Container, Card, Title, Subtitle, Button } from "./styles";
import { useNavigate } from "react-router-dom";

export const Home = () => {
    const navigate = useNavigate()
    return(
        <Container>
            <Card>
                <Title>ERP Manager</Title>
                    <Subtitle>Sistema de gerenciamento empresarial</Subtitle>
                    <Button variant="primary"   onClick={() => {
                        navigate("/login")
                    }}>
                     Entrar no Sistema
                    </Button>
                    <Button variant="secondary" onClick={() => {
                        navigate("/cadastro")
                    }}>
                    Cadastrar Empresa
                    </Button>
            </Card>
        </Container>
    )
}

// angularPOC/src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent {
  constructor(private router: Router) {
  }
  entrar() {
    this.router.navigate(['/login']);
  }
  cadastrar() {
    this.router.navigate(['/cadastro']);
  }
}
<div class="container">
    <div class="card">
      <h1 class="title">ERP Manager</h1>
      <p class="subtitle">Sistema de gerenciamento empresarial</p>
  
      <button class="btn primary" (click)="entrar()">Entrar no Sistema</button>
      <button class="btn secondary" (click)="cadastrar()">Cadastrar Empresa</button>
    </div>
  </div>
